[package]
name = "sd-win"
version = "0.6.0"
edition = "2021"

[dependencies]
sd-common = { path = "../common" }
serde_json = { workspace = true }

windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Media_Audio",
    "Win32_System_Com",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_DataExchange",
    "Win32_System_Memory",
] }

